### ISSUE TITLE
Implement a DWARF expressions interpreter

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#11]
Section 2.5 of the DWARF 4 standard.

@tromey was showing me a really cool way to fuzz this, but I forget the details...

**Comment by tromey** [comment]
This test case for gdb tests most of the opcodes and has the debugger go into an infinite loop if anything is implemented incorrectly:

https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/testsuite/gdb.dwarf2/pr10770.c;h=64dfc91ce751c45d5c674d25c137c50a42e95e3c;hb=HEAD

However for your case I think unit tests would be preferable.

**Comment by tromey** [comment]
There are a couple of issues here.

One is that it's handy to separate decoding of the DWARF expression from the interpretation of the expression.  For example, gdb has multiple uses for these expressions: not just evaluation; but also determining if an expression requires a stack frame (this may be idiosyncratic to gdb); compilation to gdbserver agent expressions; compilation to C for the `compile` feature; and finally good old disassembly of the expression itself.

In gdb some of these routines do their own decoding; which has led to bugs due to minor discrepancies and oversights.  I think this can be handled better (and I think elfutils does this) by having one function decode a particular opcode (operating on the `&[u8]`) into some higher-level `enum` (e.g., mapping all the `DW_OP_regXXX` values to a single `Register{value}`).

The more major issue is that a DWARF expression evaluator requires access to things it doesn't know.  For example it has to be able to read memory or fetch register values.  There are several such things, though (I can write up the full list if you want).  So the question is how to handle this.  In the relevant part of gdb it is done via callbacks with some caller-supplied object, which in Rust terms might be trait objects, though I understand those are frowned upon.  Another choice is to make everything generic, though that's unsatisfying for code explosion reasons.  Yet another possibility would be to have the base evaluator handle everything it can, sometimes returning a special result holding an operation that the caller must handle before restarting the evaluation.

**Comment by philipc** [comment]
> The more major issue is that a DWARF expression evaluator requires access to things it doesn't know. 

I haven't looked into this a lot yet, but I was thinking that we would need to have some way of allowing the caller to specify callbacks. There's a few ways of doing that:

- caller passes a struct containing function pointers and a context arg. This is equivalent to what you would do in C.
- caller passes a trait object. There's nothing wrong with trait objects if you need to use them, and in this case we do. Their performance is identical to the first option. The only disadvantage I can see is that you can't mix and match the function pointers at runtime; you have to use one of the predefined virtual tables from a specific trait implementation. They're easier to use than a struct of function pointers though.
- evaluator is generic over the trait, which can be faster than trait objects, but has the code explosion problem. However, the user always has the choice to monomorphize for a single trait implementation that itself simply delegates to some other trait object, which gets you back to the equivalent of trait objects, just in a round about way.

For returning special results, it might be tricky to manage the state and make it fast.

Another option is that the user has to implement the main evaluator loop that iterates through the opcodes, but we provide library functions that the user can call to evaluate the various opcodes, and the user provides the external information as parameters to those functions, or maybe in some cases completely implements the opcode themselves. We could also implement one of the callback options on top of this.

**Comment by tromey** [comment]
Maybe one problem with the callback approach is that the errors that the callback may want to return will depend on the particular implementation.

**Comment by fitzgen** [comment]
> caller passes a trait object. There's nothing wrong with trait objects if you need to use them, and in this case we do. Their performance is identical to the first option.

This is what I would intuitively lean towards.

The idea of returning continuations is tempting... I think until `return impl Trait` is finalized this isn't feasible; we just won't be able to melt away the abstraction due to current boxing requirements.

> The only disadvantage I can see is that you can't mix and match the function pointers at runtime; you have to use one of the predefined virtual tables from a specific trait implementation. They're easier to use than a struct of function pointers though.

Couldn't you implement the trait for any struct with `Fn(T) -> U` members etc and then allow construction of this struct at runtime? Or would this disable trait objects because of being a generic implementation? I always forget the trait object rules...

Worst case scenario, you could make it doubly indirect, but that is :(

----------------------------

> The more major issue is that a DWARF expression evaluator requires access to things it doesn't know. For example it has to be able to read memory or fetch register values. There are several such things, though (I can write up the full list if you want).

I think such a compilation would be very helpful for making this discussion a little more concrete. Thanks @tromey!

**Comment by fitzgen** [comment]
> One is that it's handy to separate decoding of the DWARF expression from the interpretation of the expression.

Totally.

I want to do something like libLUL does where it actually compiles the expressions down to machine code to get really super unwinding. I don't think that belongs in this library, but this library should definitely enable that by exposing the parser.

**Comment by philipc** [comment]
> Couldn't you implement the trait for any struct with Fn(T) -> U members etc and then allow construction of this struct at runtime?

Yeah, those options aren't mutually exclusive, so you can put function pointers in your trait object too, etc.

**Comment by tromey** [comment]
> I think such a compilation would be very helpful for making this discussion a little more concrete

FWIW I have some preliminary work toward this bug - I wrote the decoding step and many of the evaluation cases.  There's still quite a bit to do; e.g., nothing compiles.

My list of needed callbacks is:

* Dereference a pointer.  There are two flavors of this, to support the `DW_OP_xderef*` opcodes (though afaik nobody uses those, as gdb doesn't implement them).

* Get a register's value.

* Compute the frame base from `DW_AT_frame_base`.

* Get the "object address".  This could easily be done as some sort of parameter to the evaluator, though.

* Compute the location of a thread-local.

* Get the CFA.

* Given a CU offset, look up the corresponding DIE and return its `DW_AT_location`, needed to implement `DW_OP_call*`.

The evaluator probably needs some sort of maximum-instructions parameter to prevent DoS by bad DWARF.  (gdb doesn't have this but you can C-c your way out.)

@fitzgen - link to libLUL?  I couldn't find it.

**Comment by fitzgen** [comment]
> @fitzgen - link to libLUL? I couldn't find it.

http://searchfox.org/mozilla-central/source/tools/profiler/lul

Written by jseward, but maybe a bit of abandon-ware now -- I don't think the SPS profiler is using it anymore (I think due to lack of cross platform support?). I talked to him in London and he convinced me of the general approach.

**Comment by fitzgen** [comment]
@tromey marking this "assigned" to you

**Comment by tromey** [comment]
It compiles now.  It's feature complete vis a vis DWARF 4.  I haven't yet implemented any of the GNU extensions; I think none of them are required for unwinding, but at least one is needed for compute thread-local variables (gcc generally uses a different opcode for this, I've filed a bug).  I figure that extensions can comfortably be sent as follow-up patches.

I haven't written the tests yet, hence no PR.  I have a few questions and comments.

* It's split into two parts -- decode a single operation into an enum, and then a general decode-and-evaluate loop.  It could be split further so that there's an evaluator single-step operation.  However this seemed more expensive and complicated to me, without any advantage I could see, so I didn't bother.

* I didn't make it very pedantic.  For example there are various opcodes that are invalid in certain contexts; but I didn't bother diagnosing this.  If this is worth doing it's not a big deal.

* I put the new errors, including new errors from the evaluator, into `ParseResult`.  But this is a bit odd because the evaluation errors are not really "parse" errors.  I'm wondering if you'd want me to introduce a new `EvaluationResult`.  I suppose it would have to wrap a `ParseResult` due to the decoding step in the evaluator.

* I haven't written handy functions for the various evaluator callbacks that reference DWARF (frame base, call frame CFA, and the one to implement `DW_OP_call*`.  One idea would be to change the API to the evaluator so that it's required to pass in the whole section plus the current CU, and then just not have these be callbacks.  Another idea is to just leave a few convenience functions around for the normal case where you want to use them.

**Comment by philipc** [comment]
> It's split into two parts -- decode a single operation into an enum, and then a general decode-and-evaluate loop. It could be split further so that there's an evaluator single-step operation.

Sounds fine how it is. The only possible use I can see for single-step is it might help for writing the tests.

> I didn't make it very pedantic. For example there are various opcodes that are invalid in certain contexts; but I didn't bother diagnosing this.

If it's not going to cause safety problems for the caller then that's fine. We're not implementing a dwarf checker at this stage. We can add more checks as needed.

> I put the new errors, including new errors from the evaluator, into ParseResult. But this is a bit odd because the evaluation errors are not really "parse" errors. I'm wondering if you'd want me to introduce a new EvaluationResult. I suppose it would have to wrap a ParseResult due to the decoding step in the evaluator.

I'm wary of adding complexity to the error handling in performance sensitive code.

> I haven't written handy functions for the various evaluator callbacks that reference DWARF (frame base, call frame CFA, and the one to implement DW_OP_call*. One idea would be to change the API to the evaluator so that it's required to pass in the whole section plus the current CU, and then just not have these be callbacks. Another idea is to just leave a few convenience functions around for the normal case where you want to use them.

I don't think I know enough about this yet. I suspect though that the current `UnitHeader` isn't suitable for passing in. eg we should have something that caches the top CU DIE, and we probably want to cache other information too. That might depend on the caller's use case though, in which case it would make sense to keep callbacks so they can customize it.

**Comment by fitzgen** [comment]
> It compiles now.

\o/

> It's feature complete vis a vis DWARF 4.

\o/

> I figure that extensions can comfortably be sent as follow-up patches.

Most indeededly.

> It's split into two parts -- decode a single operation into an enum, and then a general decode-and-evaluate loop. It could be split further so that there's an evaluator single-step operation. However this seemed more expensive and complicated to me, without any advantage I could see, so I didn't bother.

SGTM.

> I didn't make it very pedantic. For example there are various opcodes that are invalid in certain contexts; but I didn't bother diagnosing this. If this is worth doing it's not a big deal.

I didn't do this for the line number programs either (for example there is a requirement that the program end with an "end sequence" opcode that we don't currently bother verifying).

Time will tell, but my intuition is that it is not that big of a deal, and we can always land follow ups.

> I put the new errors, including new errors from the evaluator, into ParseResult. But this is a bit odd because the evaluation errors are not really "parse" errors. I'm wondering if you'd want me to introduce a new EvaluationResult. I suppose it would have to wrap a ParseResult due to the decoding step in the evaluator.

IMO we should rename `gimli::ParseError` to `gimli::Error` and avoid wrapping and exposing different error types.

> I haven't written handy functions for the various evaluator callbacks that reference DWARF (frame base, call frame CFA, and the one to implement DW_OP_call*. One idea would be to change the API to the evaluator so that it's required to pass in the whole section plus the current CU, and then just not have these be callbacks. Another idea is to just leave a few convenience functions around for the normal case where you want to use them.

I don't have much to add to what @philipc said here. I need to give this part of the standard a closer read. In the meantime, I defer to you.

**Comment by tromey** [comment]
I wrote a test and it successfully computed that 23+23=46.  So yay!

While there are many, many more tests to write, I think it is also a reasonable time to review it for API sanity, naming (which I really punted terribly), etc.

I'm still not sure what to do about the way that the callbacks have to return the same kinds of errors that are exposed by the parser.  This seems pretty limiting.  As an extreme example, a TLS lookup could involve communicating with a remote gdbserver, so one might plausibly want to wrap up a network error of some kind.

I wrote some functions like `parse_u8e` that wraps `parse_u8` with an `EndianBuf`.  Maybe all these low-level things should just always take an `EndianBuf`?

Branch is here: https://github.com/tromey/gimli/tree/dw-expr
I'm generally force-pushing to it to keep the patches clean but I can change my ways if you'd prefer.

**Comment by fitzgen** [comment]
> I wrote a test and it successfully computed that 23+23=46. So yay!

\o/

Force pushing is fine.

Want to open a PR against this repo? That will let us have a place to consolidate conversations and comment on code directly. We can hold off on merging it until it's ready, despite having the PR open.

**Comment by fitzgen** [comment]
> I'm still not sure what to do about the way that the callbacks have to return the same kinds of errors that are exposed by the parser. This seems pretty limiting. As an extreme example, a TLS lookup could involve communicating with a remote gdbserver, so one might plausibly want to wrap up a network error of some kind.

We could add a `UserDefined(Box<std::error::Error>)` variant to `ParseResult` as a catchall for this.

**Comment by philipc** [comment]
> I wrote some functions like parse_u8e that wraps parse_u8 with an EndianBuf. Maybe all these low-level things should just always take an EndianBuf?

We could add parse functions to `EndianBuf` to avoid the slightly cryptic function name. eg you would call `buf.parse_u8()` instead of `parse_u8e(buf)`.

I wouldn't mind if everything took `EndianBuf`. It should be zero-cost. It may mean additional copies of some functions though (I don't know how smart rust is about combining identical monomorphizations).

**Comment by fitzgen** [comment]
> It may mean additional copies of some functions though (I don't know how smart rust is about combining identical monomorphizations).

My understanding was that rustc doesn't do any combination of identical monomorphizations, however the best way to find out would be to try it in a play link and see.

That said, we are inlining all these functions anyways...

**Comment by fitzgen** [comment]
> We could add parse functions to EndianBuf to avoid the slightly cryptic function name. eg you would call buf.parse_u8() instead of parse_u8e(buf).
> 
> I wouldn't mind if everything took EndianBuf. It should be zero-cost.

Either way works for me -- no strong opinions.

**Comment by tromey** [comment]
I think this one can be closed now.

**Comment by fitzgen** [comment]
Thanks for the reminder :)
