### ISSUE TITLE
Consider not fully parsing CIEs when iterating an unwinding section's CFI entries

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#137]
For FDEs, we are forced to do a lazy/partial parse because we need the CIE to parse the FDE. However, we should also consider not parsing a CIE fully either. If there are a bunch of leading CIEs that won't be used by any FDE we want to examine, then we might be able to avoid parsing them completely, which might be a performance win.

Probably should wait until #114 is fixed, so we can measure any performance changes.

**Comment by philipc** [comment]
https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/ehframechpt.html specifies only one CIE, so we should ensure we can at least optimize for that case.

**Comment by fitzgen** [comment]
> https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/ehframechpt.html specifies only one CIE, so we should ensure we can at least optimize for that case.

I don't thinkg that's actually true, but the wording is a bit tricky.

It says:

> The .eh_frame section shall contain 1 or more Call Frame Information (CFI) records. The number of records present shall be determined by size of the section as contained in the section header. Each CFI record contains a Common Information Entry (CIE) record followed by 1 or more Frame Description Entry (FDE) records. Both CIEs and FDEs shall be aligned to an addressing unit sized boundary.

So there are one or more "records" and a record is a single CIE followed by one or more FDEs. Since there are potentially many "records" there are potentially many CIEs as well.

**Comment by philipc** [comment]
Yep you're right. It's still a similar optimization that is needed though: for any FDE, the most recently parsed CIE is most likely the one we need, so we should be caching the `address_size/segment_size` from that instead of parsing it again in `cie_from_offset`.  And then an additional optimization is to initially only parse the `address_size/segment_size` from the CIE, and lazily parse the rest (which is your original suggestion).

**Comment by fitzgen** [comment]
SGTM

**Comment by philipc** [comment]
I implemented partial parsing of CIEs, but it had no noticeable effect on the benchmarks. I think this is because there are only a very small number of CIEs (21 CIEs and 3482 FDEs for the test fixture). So probably better to keep the code simpler.

Not sure what I was thinking in my other comments anymore, but I don't think it was relevant to this issue. Parsing only `address_size/segment_size` is not an option because we need the address encoding from the augmentation too.
