### ISSUE TITLE
Provide `NativeEndian` default for generic `Endianity` type parameters

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#163]
Almost all of our code is generic over an `Endian` type parameter, with the bound `where Endian: Endianity`.

We should default to the `NativeEndianity` for these type parameters.

So this

```rust
struct Whatever<Endian>
    where Endian: Endianity
{
    ...
}
```

would become

```rust
struct Whatever<Endian = NativeEndianity>
    where Endian: Endianity
{
    ...
}
```

We could do this all in one go, or incrementally with a PR for a each module at a time. Whatever works for whoever wants to pick this up.

**Comment by Geemili** [comment]
Can I take this?

**Comment by fitzgen** [comment]
@Geemili sure thing! Let me know if you have any questions :)

**Comment by Geemili** [comment]
@fitzgen I'm sorry, but I haven't been able to make time for this. If someone else wants to take this issue, they can.

**Comment by fitzgen** [comment]
No problem :)

**Comment by gchamp20** [comment]
Hi,

I was looking into this and I think this is not an issue anymore with the introduction of the Reader trait.
Most structures that would have benefited from this now look like:

```rust
struct Whatever<R>
    where R: Reader  
{
    ...  
}  
````

The endianity is passed as a parameter to the builder pattern. We can't use optional parameters (yet.. [RFC #323](https://github.com/rust-lang/rfcs/issues/323)), so I assume there's no way of implementing this currently?

**Comment by philipc** [comment]
Yeah I think you're right. The only place I can see that could still default is on `struct EndianBuf`, but that doesn't help because it has an `endian` field now, so would need optional parameters too. Plus I'm not sure that using an optional endian parameter is a good idea when using `RunTimeEndian`. That might lead to obscure bugs.

We also can't default `Reader = EndianBuf<'input, NativeEndian>` because of the lifetime parameter.

Thanks for looking into this!
