### ISSUE TITLE
UnwindTableRow should have a reference to its FDE

### ISSUE THREAD

**Issue by roblabla** [gimli-rs/gimli#311]
Hey,

I'm currently writing a rust version of libunwind, to achieve pure-rust libpanic_unwind in my toolchain. To this end, I'm using gimli to parse the DWARF information, and using `unwind_info_for_address` to let gimli handle all the dirty details. Unfortunately, `UnwindTableRow` lacks a lot of information: It doesn't have the address of the personality function, the register number of the return address, or the address of the LSDA.

To this end, maybe UnwindTableRow should have a reference to its FDE and CIE ?

**Comment by main--** [comment]
[unwind-rs](https://github.com/gimli-rs/unwind-rs) may be relevant for what you're doing. It is a functional x86_64 unwinder and backtracer that also [implements](https://github.com/gimli-rs/unwind-rs/blob/14b0ccfcd88caaa953191429ab51a638895b8c2f/unwind/src/libunwind_shim.rs) the libunwind API. I have successfully used it to unwind Rust code.

You are correct that `unwind_info_for_address` does not produce all of the required information for this task which is why unwind-rs implements [its own version](https://github.com/gimli-rs/unwind-rs/blob/14b0ccfcd88caaa953191429ab51a638895b8c2f/unwind/src/lib.rs#L106) of that function. Although I'm not entirely sure how exactly a "perfect" API for this in gimli would look like.

Development on unwind-rs has stalled for now as I always was the only developer and I'm tied up in other things. But if it matches your use case (sounds like it might) I would always appreciate contributions!

**Comment by roblabla** [comment]
This indeed looks like it might do what I want, although my target of interest is aarch64. The fixes to make it all work should be minimal - I believe it basically comes down to fixing the registers ?

**Comment by main--** [comment]
>This indeed looks like it might do what I want, although my target of interest is aarch64. The fixes to make it all work should be minimal - I believe it basically comes down to fixing the registers ?

I think adjusting the registers and the glue code should do the trick, yes.

**Comment by philipc** [comment]
I think this was fixed by #316?

**Comment by roblabla** [comment]
No. Unwind-rs doesn't use `unwind_info_for_address` because it is missing too much information. Instead, it has its own implementation that wraps the structs and gets some more information.
