### ISSUE TITLE
Add DWARF writing capabilities to gimli

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#327]
## Summary

Add DWARF writing capabilities to `gimli`.

## Motivation

* Allow compilers written in Rust (e.g. [Cranelift](https://github.com/CraneStation/cranelift); cc @sunfishcode) to easily generate DWARF.

* Allow binary instrumenters (i.e. binary to binary compilers) to fix debug info for their modifications. For example, we will likely need to eventually fix up DWARF in the `.wasm` binaries that we are post processing in [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen) (cc @alexcrichton).

* Enable property-based testing (e.g. [quickcheck](https://github.com/BurntSushi/quickcheck)) where we can assert that properties like this hold for all inputs:

  ```rust
  fn round_trip_is_equal(op: gimli::Operation<...>) -> bool {
      let mut buf = vec![];
      op.write(&mut buf).unwrap();
      let new_op = gimli::Operation::parse(gimli::EndianSlice::new(&buf)).unwrap();
      op == new_op
  }
  ```

## Details

Every public struct that represents a parsed DWARF thing would get

1. a `write` method, and
2. a `from_parts` constructor for creating arbitrary instances that don't reflect something parsed from an extant debug section.

(This would be added to almost every public type, but not `gimli::StateMachine` and friends that represent *interpreters* for the parsed structures. The equivalent in writer API would be higher-level builders for writing out--for example--whatever line number opcodes are necessary to make the next row in the line number table be X. I propose *not* adding these higher-level builder APIs until we have direct experience writing DWARF with the lower-level APIs.)

### The `write` Method

The `write` method would have this signature:

```rust
use std::io;

fn write<W>(&self, out: &mut W) -> io::Result<usize>
where
    W: io::Write;
```

And it returns the number of bytes written upon success.

#### Open Questions

* Should this be generalized into a `gimli::Write` trait?

### The `from_parts` Constructors

The `from_parts` constructors will take an argument for each field of the `Self` struct, and allow creating arbitrary instances for writing. For example, `gimli::FrameDescriptionEntry::from_parts` would take an offset, length, format, common information entry, initial segment, initial address, address range, optional augmentation, and CFI instructions.

#### Open Questions

* How to write `length`-prefixed structures? Does writing assume that the `from_parts` was constructed correctly? How can producers know the right `length` without writing out all the LEB128s? Do we need to build up a rope-like data structure or use something like `test-assembler`?
* What about structures that are lazily parsed, like `gimli::DebuggingInformationEntry`s? Are producers forced to write out the attributes and children first, then construct and copy them into the DIE with `from_parts`, and then write the whole thing out again?

## Alternative Approaches

This proposal is an attempt to minimize extensions to the current API surface. But it has some drawbacks, that I think are most visible in the open questions about the `from_parts` constructors.

An alternative approach would be to add a new `write` module with definitions of all the same DWARF structures that are specialized for writing DWARF. There would be `From<&'a DebuggingInformationEntry> for write::DebuggingInformationEntry` conversions. This would most likely get us a better API for writing DWARF at the end of the day, but it would be more code to maintain.

**Comment by fitzgen** [comment]
@philipc @tromey: interested in your thoughts on this!

**Comment by fitzgen** [comment]
The more I think about it, the more I think we should bite the bullet and just define a whole new `write` module. There just isn't that much to reuse, and trying to bend over backwards to reuse types isn't going to help.

**Comment by sunfishcode** [comment]
Random idea: split the length fields etc. out of the main types. Those fields are mainly of interest to decoders themselves, rather than users of their APIs. So for example the reader APIs could return the lengths as separate values in case anyone actually needs them, but then the writer could share the main types, and just compute the lengths of things it needs itself.

**Comment by philipc** [comment]
> Should this be generalized into a gimli::Write trait

Yes I think so.  I don't think `io::Write` is enough because we need the ability to go back and write a length or an offset (eg `DW_AT_sibling`). `io::Write + io::Seek` isn't enough either, since we need to be able to tell the current offset too.

> The more I think about it, the more I think we should bite the bullet and just define a whole new write module. There just isn't that much to reuse, and trying to bend over backwards to reuse types isn't going to help.

Yes I agree. I think a builder API that writes as you go will be more natural to use and more efficient than needing to create all the parts, assemble the parts into a whole, and then write.

**Comment by philipc** [comment]
Looking at llvm and libdwarf, they both build up all the debug info in memory before writing it. This allows them to calculate offsets and lengths before writing (and other stuff too, like ranges). So that's probably a better way to do it, and my previous comment about a `Write` may not apply. I still think we want builder APIs (eg `DIE::add_attr`) rather than `from_parts`, and still agree that a separate `write` module is better.

**Comment by philipc** [comment]
The main reason that we don't want to reuse the parser data structures is that they mostly borrow the unparsed input bytes, whereas the write data structures are going to be better as owned/reference counted data structures. `Cow` or similar doesn't solve that, because it'd still be unparsed bytes.

**Comment by tromey** [comment]
It seems to me that if you want to support "traditional" compilers (ahead-of-time + separate compilation), then you definitely need a higher-level view, because writing the DWARF will require relocations to be emitted as well.

**Comment by philipc** [comment]
What do you mean by higher level view? Do you mean like how in LLVM the DWARF generation is a level above the `AsmPrinter` (which I think is where relocations are handled)?

**Comment by tromey** [comment]
Many constructs require some sort of relocation entry in the `.o`; this requires some knowledge of what the bits mean to do it properly.  Not sure if this is helpful, feel free to ignore if not.

**Comment by philipc** [comment]
I'm going to start looking into implementing this (unless someone else already is).

@sunfishcode Would it make sense for me to start doing something on the cranelift side at the same time? eg https://github.com/CraneStation/cranelift/issues/350

**Comment by sunfishcode** [comment]
@philipc Sure. And I'd be happy to help answer any questions you have, or review patches.

**Comment by fitzgen** [comment]
Woo! Great! I have a new project that will likely need DWARF writing as well, so I will have a change to exercise the APIs as well (and help with impl too of course!)

**Comment by philipc** [comment]
> An alternative approach would be to add a new `write` module with definitions of all the same DWARF structures that are specialized for writing DWARF.

This is the approach I'm taking. Just wondering about the high level structure:
- should it be another crate instead of a `write` module, since there may not be much overlap?
- if a module, should we move the existing parser into a `read` module? This may reduce confusion when reading the conversion code, since it will be clearer which definitions are from parsing.

I don't feel strongly about either, but I lean towards read/write modules.

> There would be `From<&'a DebuggingInformationEntry>` for `write::DebuggingInformationEntry` conversions.

Until we support writing everything that we read, I don't think we can do this because the conversion may fail. And even then, there will still be things that can fail parsing during conversion because of the lazy parsing. We can still have normal methods for the conversion of course.

**Comment by fitzgen** [comment]
Having `read` and `write` modules sounds good to me. We may want to add features to enable each of them so that compilation times don't blow up.

**Comment by philipc** [comment]
Initial write support has landed (targeted at line number information). Further work is tracked in #390
