### ISSUE TITLE
Consider adding Index trait syntax sugar for things that take FooOffset types

### ISSUE THREAD

**Issue by khuey** [gimli-rs/gimli#36]
This occurred to me when doing DebugStr but I didn't write the code for it.  Instead of having doing

`debug_str.get_str(offset)`

Perhaps we should do

`debug_str[offset]`

What do you think, @fitzgen?

**Comment by fitzgen** [comment]
The `Index` trait is too strict about the types it can return: it *has* to return a reference. In most cases, we want to return an `EndianBuf`, which is really just a `&[u8]` but since it encapsulates the reference rather than being a reference, we can't use it with `Index`.

See https://github.com/fitzgen/gimli/blob/3989b84e811e3af46feb211c5f17a0cf35690572/src/endianity.rs#L99

Now, this ends up not being an issue for `DebugStr`, since we generally want to get `&std::ffi::CStr`s out of it, but I think it makes sense to just be consistent and avoid `Index`. Personally, I don't mind an explicit `get_str` method.

I don't feel super strongly about this though, so maybe if @philipc disagrees we should do it...

**Comment by fitzgen** [comment]
But in general, yes I think adding `range{_from,_to}` methods that return `EndianBuf`s for all the various section types makes sense.

**Comment by fitzgen** [comment]
I guess `Index` wouldn't work for `DebugStr` either, since it returns a `Result` and not a reference.

**Comment by philipc** [comment]
I think we can only use `Index` if every index in `[0..len()]` is valid, and we can return a reference to it. For `DebugStr`, we could trivially ensure that by only allowing creation of `DebugStr` if the last byte is null (and then `get_str` can't fail), but that's probably getting a bit too tricky, and actually mid-string offsets aren't really valid, even though we can return a result for them.

For `EndianBuf`, we don't actually need the `Index` trait because of the `Deref` to `[u8]`, and the code compiles if we delete it.

**Comment by philipc** [comment]
I haven't felt a need for either `Index` or `range`. I think this is something that user code rarely needs to do. Closing, but feel free to reopen if you disagree.
