### ISSUE TITLE
Incorrect Location from DW_Op evaluator when value left on stack

### ISSUE THREAD

**Issue by crzysdrs** [gimli-rs/gimli#572]
CFA Expression from `.eh_frame`

```
  def_cfa_expression 3
          [ 0] breg5 -8
          [ 2] deref
```

Corresponding set of Evaluation instructions:
```
  DW_CFA_def_cfa_expression (...)
                        RegisterOffset { register: Register(5), offset: -8, base_type: UnitOffset(0) }
                        Deref { base_type: UnitOffset(0), size: 4, space: false }
```

This set of instructions will:
1) Request the value of Reg5 (offset by -8)
2) Request the memory pointed to by that address

The current implementation provides a `Location::Address` for the result `Piece`, when the value on the stack is a `Location::Value`. This incorrectly requires the user when piecing together the result value to dereference the `Piece` unnecessarily a second time.

This assumes I am correctly interpreting the `Location` docs, which suggest that a `Location::Address` should be looked up in memory, otherwise it should be a `Location::Value`.

[Location Docs](https://docs.rs/gimli/0.25.0/gimli/read/enum.Location.html) for `Location::Address`: "The piece is found in memory."

**Comment by philipc** [comment]
The current behaviour seems correct to me.  You are evaluating the expression in order to calculate an address, and `Location::Address` is giving you that address, no need to deref it again.

The terminology here might be confusing because this is also used for location descriptions, and for that the value on the stack is definitely an address, not a value (where possible, location descriptions return the address of the value, not the value).

**Comment by crzysdrs** [comment]
Yeah, looks like I got hung up on the terminology and went down the wrong path.
