### ISSUE TITLE
Investigate using the test-assembler crate for programmatically building binary test input

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#66]
https://crates.io/crates/test-assembler

Would make some of these big binary test inputs easier to construct. It's a Rust port of a similar library @JimBlandy wrote when writing Google Breakpad's DWARF CFI support.

Worth adopting?

**Comment by philipc** [comment]
Looks useful. I wonder how close to a full DWARF writer we'll get in the process.

**Comment by jimblandy** [comment]
I haven't used the Rust version, but with the C++ version it was very easy to add some dumb function to write out, say, a CFI header, that was fine for tests, but didn't make for an attractive API for a library.

For an example of the C++ library in use, see Firefox's [Breakpad unit tests][1].

[1]: https://hg.mozilla.org/mozilla-central/file/ca24710db69a/toolkit/crashreporter/google-breakpad/src/common/dwarf/dwarf2reader_cfi_unittest.cc#l2174

**Comment by jimblandy** [comment]
The code [here][1] is a nice example of the power of the (C++) test-assembler API. It uses it to write out an ELF file containing a DWARF CFI section whose contents are passed as an argument.

Note the way it uses labels:

- To avoid having to compute the offset of the section header table, it emits a not-yet-defined label's value into the ELF header, and then uses the `mark` method to define the label when it gets around to emitting the table.

- The section names are stored in a section themselves. The code emits the names into a separate `CFISection` object, using labels to capture the starting offset of each name,  and then uses those labels when writing the section table entries.

None of this is anything that can't be done otherwise, using straightforward code. The advantage is meant to be simplicity of expression.

[1]: https://hg.mozilla.org/mozilla-central/file/ca24710db69a/toolkit/crashreporter/google-breakpad/src/common/dwarf/dwarf2reader_cfi_unittest.cc#l2353

**Comment by philipc** [comment]
Done.
